// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace KnoWhy.iOS.Base.lproj
{
	public partial class IPadRootViewController : UIViewController
	{
		public IPadRootViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
