// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace KnoWhy.iOS
{
	public partial class RootSplitViewControllerIPad : UISplitViewController
	{
        public static RootSplitViewControllerIPad current = null;

		public RootSplitViewControllerIPad (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            current = this;
            //Delegate = new MainSplitViewControllerDelegate();
            //PreferredDisplayMode = UISplitViewControllerDisplayMode.AllVisible;
            adjustDisplayMode();

            /*UIViewController controller0 = this.ViewControllers[0];
            UIViewController controller1 = this.ViewControllers[1];

            Console.WriteLine();*/
        }

        public override void ViewWillTransitionToSize(CGSize toSize, IUIViewControllerTransitionCoordinator coordinator)
        {
            base.ViewWillTransitionToSize(toSize, coordinator);

            adjustDisplayMode();
        }

        public void adjustDisplayMode() {
            if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.LandscapeLeft)
            {
                Console.WriteLine("Landscape");
                PreferredDisplayMode = UISplitViewControllerDisplayMode.AllVisible;
            }
            else if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.LandscapeRight)
            {
                Console.WriteLine("Landscape");
                PreferredDisplayMode = UISplitViewControllerDisplayMode.AllVisible;
            }
            else if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.Portrait)
            {
                Console.WriteLine("Portrait");
                PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
            }
            else if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.PortraitUpsideDown)
            {
                Console.WriteLine("Portrait");
                PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
            }
            else
            {
                Console.WriteLine("Unknow");
                PreferredDisplayMode = UISplitViewControllerDisplayMode.Automatic;
            }
        }


        public void hideDetail() {
            //PreferredDisplayMode = UISplitViewControllerDisplayMode.PrimaryOverlay;
        }
	}
}

public class MainSplitViewControllerDelegate : UISplitViewControllerDelegate
{
    public override bool CollapseSecondViewController(UISplitViewController splitViewController, UIViewController secondaryViewController, UIViewController primaryViewController)
    {
        return true;
    }
}
