// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace KnoWhy.iOS.Base.lproj
{
	public partial class SelectChapterViewController : UIViewController
	{
		public SelectChapterViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            this.Title = KnoWhy.Current.CONSTANT_SELECT_CHAPTER;
        }
	}
}
