// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace KnoWhy.iOS.Base.lproj
{
	public partial class SelectBookViewController : UIViewController
	{
		public SelectBookViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.Title = KnoWhy.Current.CONSTANT_SELECT_BOOK;
        }
	}
}
